-- Done by Jungwon Eom

INSERT INTO Cities VALUES ('Barcelona'	 ,'ESP');
INSERT INTO Cities VALUES ('London'	 ,'GBR');
INSERT INTO Cities VALUES ('Antwerpen'	 ,'BEL');
INSERT INTO Cities VALUES ('Paris'	 ,'FRA');
INSERT INTO Cities VALUES ('Calgary'	 ,'CAN');
INSERT INTO Cities VALUES ('Albertville'	 ,'USA');
INSERT INTO Cities VALUES ('Lillehammer'	 ,'NOR');
INSERT INTO Cities VALUES ('Los Angeles'	 ,'USA');
INSERT INTO Cities VALUES ('Salt Lake City'	 ,'USA');
INSERT INTO Cities VALUES ('Helsinki'	 ,'FIN');
INSERT INTO Cities VALUES ('Lake Placid'	 ,'USA');
INSERT INTO Cities VALUES ('Sydney'	 ,'AUS');
INSERT INTO Cities VALUES ('Atlanta'	 ,'USA');
INSERT INTO Cities VALUES ('Stockholm'	 ,'SWE');
INSERT INTO Cities VALUES ('Sochi'	 ,'RUS');
INSERT INTO Cities VALUES ('Nagano'	 ,'JPN');
INSERT INTO Cities VALUES ('Torino'	 ,'ITA');
INSERT INTO Cities VALUES ('Beijing'	 ,'CHN');
INSERT INTO Cities VALUES ('Rio de Janeiro'	 ,'BRA');
INSERT INTO Cities VALUES ('Athina'	 ,'GRE');
INSERT INTO Cities VALUES ('Squaw Valley'	 ,'USA');
INSERT INTO Cities VALUES ('Innsbruck'	 ,'AUT');
INSERT INTO Cities VALUES ('Sarajevo'	 ,'BIH');
INSERT INTO Cities VALUES ('Mexico City'	 ,'MEX');
INSERT INTO Cities VALUES ('Munich'	 ,'GDR');
INSERT INTO Cities VALUES ('Seoul'	 ,'KOR');
INSERT INTO Cities VALUES ('Berlin'	 ,'GDR');
INSERT INTO Cities VALUES ('Oslo'	 ,'NOR');
INSERT INTO Cities VALUES ("Cortina d'Ampezzo"	 ,'ITA');
INSERT INTO Cities VALUES ('Melbourne'	 ,'AUS');
INSERT INTO Cities VALUES ('Roma'	 ,'ITA');
INSERT INTO Cities VALUES ('Amsterdam'	 ,'NED');
INSERT INTO Cities VALUES ('Montreal'	 ,'CAN');
INSERT INTO Cities VALUES ('Moskva'	 ,'RUS');
INSERT INTO Cities VALUES ('Tokyo'	 ,'JPN');
INSERT INTO Cities VALUES ('Vancouver'	 ,'CAN');
INSERT INTO Cities VALUES ('Grenoble'	 ,'FRA');
INSERT INTO Cities VALUES ('Sapporo'	 ,'JPN');
INSERT INTO Cities VALUES ('Chamonix'	 ,'FRA');
INSERT INTO Cities VALUES ('St. Louis'	 ,'USA');
INSERT INTO Cities VALUES ('Sankt Moritz'	 ,'SWZ');
INSERT INTO Cities VALUES ('Garmisch-Partenkirchen'	 ,'GDR');
