-- Done by Jungwon Eom 
--Insert datas into the Region table

INSERT INTO Region VALUES (	 'AFG'	,	 'Afghanistan'	,	NULL	); 
INSERT INTO Region VALUES (	 'AHO'	,	 'Curacao'	,	 'Netherlands Antilles'	); 
INSERT INTO Region VALUES (	 'ALB'	,	 'Albania'	,	NULL	); 
INSERT INTO Region VALUES (	 'ALG'	,	 'Algeria'	,	NULL	); 
INSERT INTO Region VALUES (	 'AND'	,	 'Andorra'	,	NULL	); 
INSERT INTO Region VALUES (	 'ANG'	,	 'Angola'	,	NULL	); 
INSERT INTO Region VALUES (	 'ANT'	,	 'Antigua'	,	 'Antigua and Barbuda'	); 
INSERT INTO Region VALUES (	 'ANZ'	,	 'Australia'	,	 'Australasia'	); 
INSERT INTO Region VALUES (	 'ARG'	,	 'Argentina'	,	NULL	); 
INSERT INTO Region VALUES (	 'ARM'	,	 'Armenia'	,	NULL	); 
INSERT INTO Region VALUES (	 'ARU'	,	 'Aruba'	,	NULL	); 
INSERT INTO Region VALUES (	 'ASA'	,	 'American Samoa'	,	NULL	); 
INSERT INTO Region VALUES (	 'AUS'	,	 'Australia'	,	NULL	); 
INSERT INTO Region VALUES (	 'AUT'	,	 'Austria'	,	NULL	); 
INSERT INTO Region VALUES (	 'AZE'	,	 'Azerbaijan'	,	NULL	); 
INSERT INTO Region VALUES (	 'BAH'	,	 'Bahamas'	,	NULL	); 
INSERT INTO Region VALUES (	 'BAN'	,	 'Bangladesh'	,	NULL	); 
INSERT INTO Region VALUES (	 'BAR'	,	 'Barbados'	,	NULL	); 
INSERT INTO Region VALUES (	 'BDI'	,	 'Burundi'	,	NULL	); 
INSERT INTO Region VALUES (	 'BEL'	,	 'Belgium'	,	NULL	); 
INSERT INTO Region VALUES (	 'BEN'	,	 'Benin'	,	NULL	); 
INSERT INTO Region VALUES (	 'BER'	,	 'Bermuda'	,	NULL	); 
INSERT INTO Region VALUES (	 'BHU'	,	 'Bhutan'	,	NULL	); 
INSERT INTO Region VALUES (	 'BIH'	,	 'Bosnia and Herzegovina'	,	NULL	); 
INSERT INTO Region VALUES (	 'BIZ'	,	 'Belize'	,	NULL	); 
INSERT INTO Region VALUES (	 'BLR'	,	 'Belarus'	,	NULL	); 
INSERT INTO Region VALUES (	 'BOH'	,	 'Czech Republic'	,	 'Bohemia'	); 
INSERT INTO Region VALUES (	 'BOL'	,	 'Boliva'	,	NULL	); 
INSERT INTO Region VALUES (	 'BOT'	,	 'Botswana'	,	NULL	); 
INSERT INTO Region VALUES (	 'BRA'	,	 'Brazil'	,	NULL	); 
INSERT INTO Region VALUES (	 'BRN'	,	 'Bahrain'	,	NULL	); 
INSERT INTO Region VALUES (	 'BRU'	,	 'Brunei'	,	NULL	); 
INSERT INTO Region VALUES (	 'BUL'	,	 'Bulgaria'	,	NULL	); 
INSERT INTO Region VALUES (	 'BUR'	,	 'Burkina Faso'	,	NULL	); 
INSERT INTO Region VALUES (	 'CAF'	,	 'Central African Republic'	,	NULL	); 
INSERT INTO Region VALUES (	 'CAM'	,	 'Cambodia'	,	NULL	); 
INSERT INTO Region VALUES (	 'CAN'	,	 'Canada'	,	NULL	); 
INSERT INTO Region VALUES (	 'CAY'	,	 'Cayman Islands'	,	NULL	); 
INSERT INTO Region VALUES (	 'CGO'	,	 'Republic of Congo'	,	NULL	); 
INSERT INTO Region VALUES (	 'CHA'	,	 'Chad'	,	NULL	); 
INSERT INTO Region VALUES (	 'CHI'	,	 'Chile'	,	NULL	); 
INSERT INTO Region VALUES (	 'CHN'	,	 'China'	,	NULL	); 
INSERT INTO Region VALUES (	 'CIV'	,	 'Ivory Coast'	,	NULL	); 
INSERT INTO Region VALUES (	 'CMR'	,	 'Cameroon'	,	NULL	); 
INSERT INTO Region VALUES (	 'COD'	,	 'Democratic Republic of the Congo'	,	NULL	); 
INSERT INTO Region VALUES (	 'COK'	,	 'Cook Islands'	,	NULL	); 
INSERT INTO Region VALUES (	 'COL'	,	 'Colombia'	,	NULL	); 
INSERT INTO Region VALUES (	 'COM'	,	 'Comoros'	,	NULL	); 
INSERT INTO Region VALUES (	 'CPV'	,	 'Cape Verde'	,	NULL	); 
INSERT INTO Region VALUES (	 'CRC'	,	 'Costa Rica'	,	NULL	); 
INSERT INTO Region VALUES (	 'CRO'	,	 'Croatia'	,	NULL	); 
INSERT INTO Region VALUES (	 'CRT'	,	 'Greece'	,	 'Crete'	); 
INSERT INTO Region VALUES (	 'CUB'	,	 'Cuba'	,	NULL	); 
INSERT INTO Region VALUES (	 'CYP'	,	 'Cyprus'	,	NULL	); 
INSERT INTO Region VALUES (	 'CZE'	,	 'Czech Republic'	,	NULL	); 
INSERT INTO Region VALUES (	 'DEN'	,	 'Denmark'	,	NULL	); 
INSERT INTO Region VALUES (	 'DJI'	,	 'Djibouti'	,	NULL	); 
INSERT INTO Region VALUES (	 'DMA'	,	 'Dominica'	,	NULL	); 
INSERT INTO Region VALUES (	 'DOM'	,	 'Dominican Republic'	,	NULL	); 
INSERT INTO Region VALUES (	 'ECU'	,	 'Ecuador'	,	NULL	); 
INSERT INTO Region VALUES (	 'EGY'	,	 'Egypt'	,	NULL	); 
INSERT INTO Region VALUES (	 'ERI'	,	 'Eritrea'	,	NULL	); 
INSERT INTO Region VALUES (	 'ESA'	,	 'El Salvador'	,	NULL	); 
INSERT INTO Region VALUES (	 'ESP'	,	 'Spain'	,	NULL	); 
INSERT INTO Region VALUES (	 'EST'	,	 'Estonia'	,	NULL	); 
INSERT INTO Region VALUES (	 'ETH'	,	 'Ethiopia'	,	NULL	); 
INSERT INTO Region VALUES (	 'EUN'	,	 'Russia'	,	NULL	); 
INSERT INTO Region VALUES (	 'FIJ'	,	 'Fiji'	,	NULL	); 
INSERT INTO Region VALUES (	 'FIN'	,	 'Finland'	,	NULL	); 
INSERT INTO Region VALUES (	 'FRA'	,	 'France'	,	NULL	); 
INSERT INTO Region VALUES (	 'FRG'	,	 'Germany'	,	NULL	); 
INSERT INTO Region VALUES (	 'FSM'	,	 'Micronesia'	,	NULL	); 
INSERT INTO Region VALUES (	 'GAB'	,	 'Gabon'	,	NULL	); 
INSERT INTO Region VALUES (	 'GAM'	,	 'Gambia'	,	NULL	); 
INSERT INTO Region VALUES (	 'GBR'	,	 'UK'	,	NULL	); 
INSERT INTO Region VALUES (	 'GBS'	,	 'Guinea-Bissau'	,	NULL	); 
INSERT INTO Region VALUES (	 'GDR'	,	 'Germany'	,	NULL	); 
INSERT INTO Region VALUES (	 'GEO'	,	 'Georgia'	,	NULL	); 
INSERT INTO Region VALUES (	 'GEQ'	,	 'Equatorial Guinea'	,	NULL	); 
INSERT INTO Region VALUES (	 'GER'	,	 'Germany'	,	NULL	); 
INSERT INTO Region VALUES (	 'GHA'	,	 'Ghana'	,	NULL	); 
INSERT INTO Region VALUES (	 'GRE'	,	 'Greece'	,	NULL	); 
INSERT INTO Region VALUES (	 'GRN'	,	 'Grenada'	,	NULL	); 
INSERT INTO Region VALUES (	 'GUA'	,	 'Guatemala'	,	NULL	); 
INSERT INTO Region VALUES (	 'GUI'	,	 'Guinea'	,	NULL	); 
INSERT INTO Region VALUES (	 'GUM'	,	 'Guam'	,	NULL	); 
INSERT INTO Region VALUES (	 'GUY'	,	 'Guyana'	,	NULL	); 
INSERT INTO Region VALUES (	 'HAI'	,	 'Haiti'	,	NULL	); 
INSERT INTO Region VALUES (	 'HKG'	,	 'China'	,	 'Hong Kong'	); 
INSERT INTO Region VALUES (	 'HON'	,	 'Honduras'	,	NULL	); 
INSERT INTO Region VALUES (	 'HUN'	,	 'Hungary'	,	NULL	); 
INSERT INTO Region VALUES (	 'INA'	,	 'Indonesia'	,	NULL	); 
INSERT INTO Region VALUES (	 'IND'	,	 'India'	,	NULL	); 
INSERT INTO Region VALUES (	 'IOA'	,	 'Individual Olympic Athletes'	,	NULL	); 
INSERT INTO Region VALUES (	 'IRI'	,	 'Iran'	,	NULL	); 
INSERT INTO Region VALUES (	 'IRL'	,	 'Ireland'	,	NULL	); 
INSERT INTO Region VALUES (	 'IRQ'	,	 'Iraq'	,	NULL	); 
INSERT INTO Region VALUES (	 'ISL'	,	 'Iceland'	,	NULL	); 
INSERT INTO Region VALUES (	 'ISR'	,	 'Israel'	,	NULL	); 
INSERT INTO Region VALUES (	 'ISV'	,	 'Virgin Islands, US'	,	 'Virgin Islands'	); 
INSERT INTO Region VALUES (	 'ITA'	,	 'Italy'	,	NULL	); 
INSERT INTO Region VALUES (	 'IVB'	,	 'Virgin Islands, British'	,	NULL	); 
INSERT INTO Region VALUES (	 'JAM'	,	 'Jamaica'	,	NULL	); 
INSERT INTO Region VALUES (	 'JOR'	,	 'Jordan'	,	NULL	); 
INSERT INTO Region VALUES (	 'JPN'	,	 'Japan'	,	NULL	); 
INSERT INTO Region VALUES (	 'KAZ'	,	 'Kazakhstan'	,	NULL	); 
INSERT INTO Region VALUES (	 'KEN'	,	 'Kenya'	,	NULL	); 
INSERT INTO Region VALUES (	 'KGZ'	,	 'Kyrgyzstan'	,	NULL	); 
INSERT INTO Region VALUES (	 'KIR'	,	 'Kiribati'	,	NULL	); 
INSERT INTO Region VALUES (	 'KOR'	,	 'South Korea'	,	NULL	); 
INSERT INTO Region VALUES (	 'KOS'	,	 'Kosovo'	,	NULL	); 
INSERT INTO Region VALUES (	 'KSA'	,	 'Saudi Arabia'	,	NULL	); 
INSERT INTO Region VALUES (	 'KUW'	,	 'Kuwait'	,	NULL	); 
INSERT INTO Region VALUES (	 'LAO'	,	 'Laos'	,	NULL	); 
INSERT INTO Region VALUES (	 'LAT'	,	 'Latvia'	,	NULL	); 
INSERT INTO Region VALUES (	 'LBA'	,	 'Libya'	,	NULL	); 
INSERT INTO Region VALUES (	 'LBR'	,	 'Liberia'	,	NULL	); 
INSERT INTO Region VALUES (	 'LCA'	,	 'Saint Lucia'	,	NULL	); 
INSERT INTO Region VALUES (	 'LES'	,	 'Lesotho'	,	NULL	); 
INSERT INTO Region VALUES (	 'LIB'	,	 'Lebanon'	,	NULL	); 
INSERT INTO Region VALUES (	 'LIE'	,	 'Liechtenstein'	,	NULL	); 
INSERT INTO Region VALUES (	 'LTU'	,	 'Lithuania'	,	NULL	); 
INSERT INTO Region VALUES (	 'LUX'	,	 'Luxembourg'	,	NULL	); 
INSERT INTO Region VALUES (	 'MAD'	,	 'Madagascar'	,	NULL	); 
INSERT INTO Region VALUES (	 'MAL'	,	 'Malaysia'	,	NULL	); 
INSERT INTO Region VALUES (	 'MAR'	,	 'Morocco'	,	NULL	); 
INSERT INTO Region VALUES (	 'MAS'	,	 'Malaysia'	,	NULL	); 
INSERT INTO Region VALUES (	 'MAW'	,	 'Malawi'	,	NULL	); 
INSERT INTO Region VALUES (	 'MDA'	,	 'Moldova'	,	NULL	); 
INSERT INTO Region VALUES (	 'MDV'	,	 'Maldives'	,	NULL	); 
INSERT INTO Region VALUES (	 'MEX'	,	 'Mexico'	,	NULL	); 
INSERT INTO Region VALUES (	 'MGL'	,	 'Mongolia'	,	NULL	); 
INSERT INTO Region VALUES (	 'MHL'	,	 'Marshall Islands'	,	NULL	); 
INSERT INTO Region VALUES (	 'MKD'	,	 'Macedonia'	,	NULL	); 
INSERT INTO Region VALUES (	 'MLI'	,	 'Mali'	,	NULL	); 
INSERT INTO Region VALUES (	 'MLT'	,	 'Malta'	,	NULL	); 
INSERT INTO Region VALUES (	 'MNE'	,	 'Montenegro'	,	NULL	); 
INSERT INTO Region VALUES (	 'MON'	,	 'Monaco'	,	NULL	); 
INSERT INTO Region VALUES (	 'MOZ'	,	 'Mozambique'	,	NULL	); 
INSERT INTO Region VALUES (	 'MRI'	,	 'Mauritius'	,	NULL	); 
INSERT INTO Region VALUES (	 'MTN'	,	 'Mauritania'	,	NULL	); 
INSERT INTO Region VALUES (	 'MYA'	,	 'Myanmar'	,	NULL	); 
INSERT INTO Region VALUES (	 'NAM'	,	 'Namibia'	,	NULL	); 
INSERT INTO Region VALUES (	 'NBO'	,	 'Malaysia'	,	 'North Borneo'	); 
INSERT INTO Region VALUES (	 'NCA'	,	 'Nicaragua'	,	NULL	); 
INSERT INTO Region VALUES (	 'NED'	,	 'Netherlands'	,	NULL	); 
INSERT INTO Region VALUES (	 'NEP'	,	 'Nepal'	,	NULL	); 
INSERT INTO Region VALUES (	 'NFL'	,	 'Canada'	,	 'Newfoundland'	); 
INSERT INTO Region VALUES (	 'NGR'	,	 'Nigeria'	,	NULL	); 
INSERT INTO Region VALUES (	 'NIG'	,	 'Niger'	,	NULL	); 
INSERT INTO Region VALUES (	 'NOR'	,	 'Norway'	,	NULL	); 
INSERT INTO Region VALUES (	 'NRU'	,	 'Nauru'	,	NULL	); 
INSERT INTO Region VALUES (	 'NZL'	,	 'New Zealand'	,	NULL	); 
INSERT INTO Region VALUES (	 'OMA'	,	 'Oman'	,	NULL	); 
INSERT INTO Region VALUES (	 'PAK'	,	 'Pakistan'	,	NULL	); 
INSERT INTO Region VALUES (	 'PAN'	,	 'Panama'	,	NULL	); 
INSERT INTO Region VALUES (	 'PAR'	,	 'Paraguay'	,	NULL	); 
INSERT INTO Region VALUES (	 'PER'	,	 'Peru'	,	NULL	); 
INSERT INTO Region VALUES (	 'PHI'	,	 'Philippines'	,	NULL	); 
INSERT INTO Region VALUES (	 'PLE'	,	 'Palestine'	,	NULL	); 
INSERT INTO Region VALUES (	 'PLW'	,	 'Palau'	,	NULL	); 
INSERT INTO Region VALUES (	 'PNG'	,	 'Papua New Guinea'	,	NULL	); 
INSERT INTO Region VALUES (	 'POL'	,	 'Poland'	,	NULL	); 
INSERT INTO Region VALUES (	 'POR'	,	 'Portugal'	,	NULL	); 
INSERT INTO Region VALUES (	 'PRK'	,	 'North Korea'	,	NULL	); 
INSERT INTO Region VALUES (	 'PUR'	,	 'Puerto Rico'	,	NULL	); 
INSERT INTO Region VALUES (	 'QAT'	,	 'Qatar'	,	NULL	); 
INSERT INTO Region VALUES (	 'RHO'	,	 'Zimbabwe'	,	NULL	); 
INSERT INTO Region VALUES (	 'ROT'	,	 'NA'	,	 'Refugee Olympic Team'	); 
INSERT INTO Region VALUES (	 'ROU'	,	 'Romania'	,	NULL	); 
INSERT INTO Region VALUES (	 'RSA'	,	 'South Africa'	,	NULL	); 
INSERT INTO Region VALUES (	 'RUS'	,	 'Russia'	,	NULL	); 
INSERT INTO Region VALUES (	 'RWA'	,	 'Rwanda'	,	NULL	); 
INSERT INTO Region VALUES (	 'SAA'	,	 'Germany'	,	NULL	); 
INSERT INTO Region VALUES (	 'SAM'	,	 'Samoa'	,	NULL	); 
INSERT INTO Region VALUES (	 'SCG'	,	 'Serbia'	,	 'Serbia and Montenegro'	); 
INSERT INTO Region VALUES (	 'SEN'	,	 'Senegal'	,	NULL	); 
INSERT INTO Region VALUES (	 'SEY'	,	 'Seychelles'	,	NULL	); 
INSERT INTO Region VALUES (	 'SIN'	,	 'Singapore'	,	NULL	); 
INSERT INTO Region VALUES (	 'SKN'	,	 'Saint Kitts'	,	 'Turks and Caicos Islands'	); 
INSERT INTO Region VALUES (	 'SLE'	,	 'Sierra Leone'	,	NULL	); 
INSERT INTO Region VALUES (	 'SLO'	,	 'Slovenia'	,	NULL	); 
INSERT INTO Region VALUES (	 'SMR'	,	 'San Marino'	,	NULL	); 
INSERT INTO Region VALUES (	 'SOL'	,	 'Solomon Islands'	,	NULL	); 
INSERT INTO Region VALUES (	 'SOM'	,	 'Somalia'	,	NULL	); 
INSERT INTO Region VALUES (	 'SRB'	,	 'Serbia'	,	NULL	); 
INSERT INTO Region VALUES (	 'SRI'	,	 'Sri Lanka'	,	NULL	); 
INSERT INTO Region VALUES (	 'SSD'	,	 'South Sudan'	,	NULL	); 
INSERT INTO Region VALUES (	 'STP'	,	 'Sao Tome and Principe'	,	NULL	); 
INSERT INTO Region VALUES (	 'SUD'	,	 'Sudan'	,	NULL	); 
INSERT INTO Region VALUES (	 'SUI'	,	 'Switzerland'	,	NULL	); 
INSERT INTO Region VALUES (	 'SUR'	,	 'Suriname'	,	NULL	); 
INSERT INTO Region VALUES (	 'SVK'	,	 'Slovakia'	,	NULL	); 
INSERT INTO Region VALUES (	 'SWE'	,	 'Sweden'	,	NULL	); 
INSERT INTO Region VALUES (	 'SWZ'	,	 'Swaziland'	,	NULL	); 
INSERT INTO Region VALUES (	 'SYR'	,	 'Syria'	,	NULL	); 
INSERT INTO Region VALUES (	 'TAN'	,	 'Tanzania'	,	NULL	); 
INSERT INTO Region VALUES (	 'TCH'	,	 'Czech Republic'	,	NULL	); 
INSERT INTO Region VALUES (	 'TGA'	,	 'Tonga'	,	NULL	); 
INSERT INTO Region VALUES (	 'THA'	,	 'Thailand'	,	NULL	); 
INSERT INTO Region VALUES (	 'TJK'	,	 'Tajikistan'	,	NULL	); 
INSERT INTO Region VALUES (	 'TKM'	,	 'Turkmenistan'	,	NULL	); 
INSERT INTO Region VALUES (	 'TLS'	,	 'Timor-Leste'	,	NULL	); 
INSERT INTO Region VALUES (	 'TOG'	,	 'Togo'	,	NULL	); 
INSERT INTO Region VALUES (	 'TPE'	,	 'Taiwan'	,	NULL	); 
INSERT INTO Region VALUES (	 'TTO'	,	 'Trinidad'	,	 'Trinidad and Tobago'	); 
INSERT INTO Region VALUES (	 'TUN'	,	 'Tunisia'	,	NULL	); 
INSERT INTO Region VALUES (	 'TUR'	,	 'Turkey'	,	NULL	); 
INSERT INTO Region VALUES (	 'TUV'	,	 'NA'	,	 'Tuvalu'	); 
INSERT INTO Region VALUES (	 'UAE'	,	 'United Arab Emirates'	,	NULL	); 
INSERT INTO Region VALUES (	 'UAR'	,	 'Syria'	,	 'United Arab Republic'	); 
INSERT INTO Region VALUES (	 'UGA'	,	 'Uganda'	,	NULL	); 
INSERT INTO Region VALUES (	 'UKR'	,	 'Ukraine'	,	NULL	); 
INSERT INTO Region VALUES (	 'UNK'	,	 'NA'	,	 'Unknown'	); 
INSERT INTO Region VALUES (	 'URS'	,	 'Russia'	,	NULL	); 
INSERT INTO Region VALUES (	 'URU'	,	 'Uruguay'	,	NULL	); 
INSERT INTO Region VALUES (	 'USA'	,	 'USA'	,	NULL	); 
INSERT INTO Region VALUES (	 'UZB'	,	 'Uzbekistan'	,	NULL	); 
INSERT INTO Region VALUES (	 'VAN'	,	 'Vanuatu'	,	NULL	); 
INSERT INTO Region VALUES (	 'VEN'	,	 'Venezuela'	,	NULL	); 
INSERT INTO Region VALUES (	 'VIE'	,	 'Vietnam'	,	NULL	); 
INSERT INTO Region VALUES (	 'VIN'	,	 'Saint Vincent'	,	NULL	); 
INSERT INTO Region VALUES (	 'VNM'	,	 'Vietnam'	,	NULL	); 
INSERT INTO Region VALUES (	 'WIF'	,	 'Trinidad'	,	 'West Indies Federation'	); 
INSERT INTO Region VALUES (	 'YAR'	,	 'Yemen'	,	 'North Yemen'	); 
INSERT INTO Region VALUES (	 'YEM'	,	 'Yemen'	,	NULL	); 
INSERT INTO Region VALUES (	 'YMD'	,	 'Yemen'	,	 'South Yemen'	); 
INSERT INTO Region VALUES (	 'YUG'	,	 'Serbia'	,	 'Yugoslavia'	); 
INSERT INTO Region VALUES (	 'ZAM'	,	 'Zambia'	,	NULL	); 
INSERT INTO Region VALUES (	 'ZIM'	,	 'Zimbabwe'	,	NULL	); 
